### ISSUE TITLE
Question: Content-DPR - this is gone?

### ISSUE THREAD

**Issue by hamishwillee** [WICG/responsive-image-client-hints#14]
`Content-DPR` appears to be gone from the old spec and not present in the new one. It's gone for good?

**Comment by eeeps** [comment]
The removal was intentional; `Content-DPR` was shelved in favor of specifying intrinsic resolution/dimensions in EXIF metadata.

[WebKit objected to Content-DPR](https://lists.webkit.org/pipermail/webkit-dev/2020-March/031143.html), on the grounds that ["image resolution is not a transport level feature."](https://bugs.webkit.org/show_bug.cgi?id=145380#c26)

WebKit were, however, amenable to the idea of reading/applying resolution metadata contained in EXIF, as long as it could be done in a web-compatible way. So, [we figured out how to do that](https://github.com/whatwg/html/pull/5574), in order to meet this and other [use cases](https://github.com/eeeps/exif-intrinsic-sizing-explainer) for giving servers (and image authoring tools!) control over intrinsic dimensions/density. EXIF-based intrinsic sizing is now shipping in Chrome and Safari, and should ship in Firefox 90.

Specifying this metadata in the response body (in different ways, for different image formats) [makes things significantly more complex](https://bugs.webkit.org/show_bug.cgi?id=145380#c15) for servers who want to modify resolution metadata as part of their delivery flow, and [reduces caching opportunities](https://github.com/WICG/responsive-image-client-hints/issues/4). OTOH, the embedded, portable, permanence of EXIF vs. `Content-DPR` is better for the EXIF-Resolution use cases that involve a static intrinsic resolution (like low-quality image placeholders, or sharing high-dpi screenshots) rather than a dynamic one (like Client Hints).

Ultimately, though, `Content-DPR` was shelved because it lacked consensus.

**Comment by hamishwillee** [comment]
Thanks very much! Makes sense.

1. Re "EXIF-based intrinsic sizing is now shipping in Chrome and Safari, and should ship in Firefox 90.". Do you happen to know what issue? I ask because I'm part of the team documenting FF90 and this is not on the roadmap and I can't find the issue on bugzilla search.

**Comment by eeeps** [comment]
[The bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1680387)
[Web Platform Test results](https://wpt.fyi/results/density-size-correction?label=master&product=firefox%5Bstable%5D&product=firefox%5Bbeta%5D&product=firefox%5Bexperimental%5D&aligned&q=density-corrected) show the feature in 90, but not 89.
